### ISSUE TITLE
ActiveRecord find and find! methods

### ISSUE THREAD

**Issue by donapieppo** [mauricew/from-activerecord-to-ecto#1]
I think that in querying.md the section for `find` in ActiveRecord 
```ruby
User.find(1)
User.find!(1) # raises ActiveRecord::RecordNotFound
```
is not correct.

In  [ActiveRecord find](https://api.rubyonrails.org/v7.1.0/classes/ActiveRecord/FinderMethods.html#method-i-findurl) is stated:
```If one or more records cannot be found for the requested ids, then [ActiveRecord::RecordNotFound](https://api.rubyonrails.org/v7.1.0/classes/ActiveRecord/RecordNotFound.html) will be raised.```
also for the simple `find`.
In fact in module [ActiveRecord](https://api.rubyonrails.org/v7.1.0/classes/ActiveRecord.html)::FinderMethods has no `find!` method FWIK.

**Comment by mauricew** [comment]
I'm shocked I had that there in the first place, thanks for bringing this to my attention, I'll make an update this week.
